SocialMediaApp/Controllers/LikesController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SocialMediaApp.Data;
using SocialMediaApp.Models;

namespace SocialMediaApp.Controllers
{
	public class LikesController : Controller
	{
		private readonly ApplicationDbContext db;
		private readonly UserManager<ApplicationUser> _userManager;
		private readonly RoleManager<IdentityRole> _roleManager;
		public LikesController(
		ApplicationDbContext context,
		IWebHostEnvironment env,
		UserManager<ApplicationUser> userManager,
		RoleManager<IdentityRole> roleManager
		)
		{
			db = context;
			_userManager = userManager;
			_roleManager = roleManager;
		}

		[HttpPost]
		public IActionResult Click(int id, string url)
		{
			// luam id-ul userului care a dat like
			var userId = _userManager.GetUserId(User);
			// selectam postarea cu id-ul dat
			var post = db.Posts.FirstOrDefault(p => p.Id == id);
			// daca userul a dat deja like, se pune unlike
			var like = db.Likes.FirstOrDefault(l => l.UserId == userId && l.PostId == id);
			if (like == null)
			{

				like = new Like
				{
					UserId = userId,
					PostId = id
				};
				db.Likes.Add(like);
				// crestem numarul de like-uri al postarii
				post.NrLikes += 1;
			}
			else
			{
				db.Likes.Remove(like);
				post.NrLikes -= 1;
			}
			db.SaveChanges();
			return Redirect(url);
		}


		[HttpGet]
		public IActionResult ShowLikes(int id)
		{
			// luam toti userii care au dat like la postare
			var users = db.ApplicationUsers
						  .Where(u => u.Likes.Any(l => l.PostId == id))
						  .Include(u => u.Likes)
						  .ToList();
			ViewBag.Users = users;
			ViewBag.UsersCt = users.Count();
			return View();
		}

	}
}

SocialMediaApp/Controllers/PostsController.cs
using Ganss.Xss;
using Humanizer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using SocialMediaApp.Data;
using SocialMediaApp.Models;
using System.Net.NetworkInformation;
using System.Runtime.CompilerServices;
using System.Text.RegularExpressions;

namespace SocialMediaApp.Controllers
{
	[Authorize(Roles = "User,Admin")]
	public class PostsController : Controller
	{
        private readonly ApplicationDbContext db;
		private readonly IWebHostEnvironment _env;
		private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
		private readonly SignInManager<ApplicationUser> _signInManager;
	
		public PostsController(
        ApplicationDbContext context,
		IWebHostEnvironment env,
		UserManager<ApplicationUser> userManager,
        RoleManager<IdentityRole> roleManager,
		SignInManager<ApplicationUser> signInManager
        )
        {
            db = context;
			_env = env;
            _userManager = userManager;
            _roleManager = roleManager;
			_signInManager = signInManager;
        }
        public IActionResult Index()
        {
			// daca nu e signed in, luam postarile persoanelor care au cont public
			var postari = db.Posts.Include("Comments")
                        .Include("Tag")
                        .Include("User")
                        .Where(p => p.User.Privacy == false && p.GroupId == null) // Exclude posts with a non-null GroupId
                        .OrderByDescending(a => a.Data);

            if (_signInManager.IsSignedIn(User)) // luam postarile persoanelor pe care le urmareste
                                                 // + postarile lui
            {
                // daca e admin luam toate postarile, indiferent 
                // daca contul e privat sau public
                if (User.IsInRole("Admin"))
                {
                    postari = db.Posts.Include("Comments")
                        .Include("Tag")
                        .Include("User")
                        .Where(p => p.GroupId == null)
                        .OrderByDescending(a => a.Data);
                }
                else
                {
                    // luam id-ul userului
                    var id = _userManager.GetUserId(User);
                    // luam lista oamenilor pe care ii urmareste
                    List<string> following = db.Follows
                                                     .Where(f => f.FollowerId == id)
                                                     .Select(f => f.FollowedId)
                                                     .ToList();
                    // luam postarile facute de oamenii pe care ii urmareste
                    postari = db.Posts.Include("Comments")
                           .Include("Tag")
                           .Include("User")
                           .Where(p => (following.Contains(p.UserId) || p.UserId == id) && p.GroupId == null) // Exclude posts with a non-null GroupId
                           .OrderByDescending(a => a.Data);
                }
            }

            var search = HttpContext.Request.Query["search"].ToString().Trim();
            if (!string.IsNullOrEmpty(search))
            {
                List<int> postIds = db.Posts.Where(at => at.Continut.Contains(search)).Select(a => a.Id).ToList();
                List<int> articleIdsOfCommentsWithSearchString = db.Comments
                    .Where(c => c.Continut.Contains(search))
                    .Select(c => (int)c.PostId).ToList();
                List<int> mergedIds = postIds.Union(articleIdsOfCommentsWithSearchString).ToList();
                postari = db.Posts.Where(postare => mergedIds.Contains(postare.Id) && postare.GroupId == null) // Exclude posts with a non-null GroupId
                                  .Include("Comments")
                                  .Include("Tag")
                                  .Include("User")
                                  .OrderByDescending(a => a.Data);
            }

            ViewBag.SearchString = search;

            int _perPage = 3;
            int totalItems = postari.Count();
            int currentPage = 1;
            if (int.TryParse(HttpContext.Request.Query["page"], out int page))
            {
                currentPage = page;
            }

            var offset = (currentPage - 1) * _perPage;
            var paginatedArticles = postari.Skip(offset).Take(_perPage);

            ViewBag.lastPage = Math.Ceiling((float)totalItems / _perPage);
            ViewBag.CurrentPage = currentPage;
            ViewBag.Posts = paginatedArticles;

            if (!string.IsNullOrEmpty(search))
            {
                ViewBag.PaginationBaseUrl = $"/Posts/Index?search={search}&page=";
            }
            else
            {
                ViewBag.PaginationBaseUrl = "/Posts/Index?page=";
            }

            SetAccessRights();
            return View();
        }


        public IActionResult Show(int id)
		{
			Post post = db.Posts.Include("Tag")
						.Include("Comments").Include("User")
						.Include("Comments.User")
						.Where(post => post.Id == id)
						.First();
			ViewBag.Comms = db.Comments
										.Include("User")
										.Where(c => c.PostId == id)
										.OrderByDescending(c => c.Data);
			SetAccessRights();
			return View(post);
		}


        // adaugarea unui comentariu din formular
        [HttpPost]
		public IActionResult Show([FromForm] Comment comment)
		{
			// luam postarea la care s-a postat comentariul
			Post post = db.Posts
						.Where(post => post.Id == comment.PostId)
						.First();
			// incrementam numarul de comentarii
			post.NrComments++;
			comment.Data = DateTime.Now;
			comment.UserId = _userManager.GetUserId(User);
            if(ModelState.IsValid)
			{
				db.Comments.Add(comment);
				db.SaveChanges();
				return Redirect("/Posts/Show/" + comment.PostId);
			}
			else
			{

				Post post1 = db.Posts.Include("Tag")
						.Include("Comments").Include("User")
						.Include("Comments.User")
						.Where(post => post.Id == comment.PostId)
						.First();

				return View(post1);
			}
		}





		// edit cu get - afisarea formularului
		[HttpGet]
		public IActionResult Edit(int id)
		{
            Post post = db.Posts.Include("Tag")
						.Where(post => post.Id == id)
						.First();
			post.Tags = GetAllTags();
            if (post.UserId == _userManager.GetUserId(User) || User.IsInRole("Admin"))
            {
                return View(post);
            }
            else
			{
                TempData["message"] = "Nu aveti dreptul sa faceti modificari asupra unui articol care nu va apartine";
				return RedirectToAction("Index");
            }
		}

		//edit cu post - salvarea datelor
		[HttpPost]
		public async Task<IActionResult> Edit(int id, Post requestPost, IFormFile? Image)
		{
			var sanitizer = new HtmlSanitizer();
			sanitizer.AllowedTags.Add("iframe");
			sanitizer.AllowedTags.Add("img");
			sanitizer.AllowedAttributes.Add("src");
			sanitizer.AllowedAttributes.Add("alt");
			Post post = await db.Posts.FindAsync(id);
            if (!(post.UserId == _userManager.GetUserId(User) || User.IsInRole("Admin")))
			{
                TempData["message"] = "Nu aveti dreptul sa faceti modificari asupra unui articol care nu va apartine";
                return RedirectToAction("Index");
            }
            if (post == null)
			{
				return NotFound();
			}

			if (!ModelState.IsValid)
			{
				requestPost.Tags = GetAllTags();
				return View(requestPost);
			}

			try
			{
				post.Continut = sanitizer.Sanitize(requestPost.Continut);
				post.Data = DateTime.Now;
				post.TagId = requestPost.TagId;
				post.Locatie = requestPost.Locatie;
				//if(requestPost.Video != null)
				//{
				//		post.Video = GetYouTubeVideoId(post.Video);
				//}	

				if (Image != null)
				{
					// Verificăm extensia
					var allowedExtensions = new[] { ".jpg", ".jpeg", ".png", ".gif", ".mp4", ".mov" };
					var fileExtension = Path.GetExtension(Image.FileName).ToLower();
					if (!allowedExtensions.Contains(fileExtension))
					{
						ModelState.AddModelError("PostImage", "Fișierul trebuie să fie o imagine(jpg, jpeg, png, gif) sau un video(mp4, mov).");
						post.Tags = GetAllTags();
						return View(post);
					}

					// Cale stocare
					var storagePath = Path.Combine(_env.WebRootPath, "images", Image.FileName);
					var databaseFileName = "/images/" + Image.FileName;

					// Salvare fișier
					using (var fileStream = new FileStream(storagePath, FileMode.Create))
					{
						await Image.CopyToAsync(fileStream);
					}
					ModelState.Remove(nameof(post.Image));
					post.Image = databaseFileName;
				}

				db.Entry(post).State = EntityState.Modified;

				TempData["message"] = "Postarea a fost editata";
				await db.SaveChangesAsync();
				return Redirect("/Posts/Show/" + post.Id);
			}
			catch (Exception ex)
			{
				Console.WriteLine($"Exception: {ex.Message}");
				requestPost.Tags = GetAllTags();
				return View(requestPost);
			}
		}

        [HttpGet]
        public IActionResult New(int? groupId = null)
        {
            var post = new Post
            {
                GroupId = groupId,
                Tags = GetAllTags()
            };
			ViewBag.Tags = GetAllTags();
            return View(post);
        }

        [Authorize(Roles = "User, Admin")]
        [HttpPost]
		public async Task<IActionResult> New(Post post, IFormFile? Image)
		{
			if (User.Identity == null || !User.Identity.IsAuthenticated)
			{
				ModelState.AddModelError("UserId", "User must be logged in to create a post.");
				post.Tags = GetAllTags();
				return View(post);
			}
            var sanitizer = new HtmlSanitizer();

SocialMediaApp/Controllers/TagsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using SocialMediaApp.Data;
using SocialMediaApp.Models;

namespace SocialMediaApp.Controllers
{
	
	public class TagsController : Controller
	{
		
		private readonly ApplicationDbContext db;
		private readonly UserManager<ApplicationUser> _userManager;
		private readonly RoleManager<IdentityRole> _roleManager;

		public TagsController(
		ApplicationDbContext context,
		UserManager<ApplicationUser> userManager,
		RoleManager<IdentityRole> roleManager
		)
		{
			db = context;
			_userManager = userManager;
			_roleManager = roleManager;
		}

		[Authorize(Roles = "Admin")]
		public IActionResult Index()
		{
            var tags = db.Tags
							  .Include(t => t.Posts)
							  .Include(t => t.User)
							  .ToList();

            // Calculate the number of posts for each tag
            foreach (var tag in tags)
            {
                tag.PostCount = tag.Posts?.Count ?? 0;
            }
            ViewBag.Tags = tags;
			return View();
		}

		[Authorize(Roles = "Admin, User")]
		public ActionResult Show(int id)
		{
			var tag = db.Tags.Find(id);
			if (tag == null)
			{
				return NotFound();
			}

			// luam postarile persoanelor cu cont public
			var posts = db.Posts
				.Include(p => p.Tag)
				.Include(p => p.Comments)
				.Include(p => p.User)
				.Where(p => p.TagId == id && p.User.Privacy == false)
				.ToList();

			if (User.IsInRole("Admin")) // adminul vede toate postarile cu eticheta res
			{
				 posts = db.Posts
					.Include(p => p.Tag)
					.Include(p => p.Comments)
					.Include(p => p.User)
					.Where(p => p.TagId == id)
					.ToList();
			}	
			ViewBag.Posts = posts;
			ViewBag.NoPosts = posts.Count();

			return View(tag);
		}

		[Authorize(Roles = "Admin")]
		public IActionResult New()
		{
			return View();
		}

		[Authorize(Roles = "Admin")]
		[HttpPost]
		public IActionResult New(Tag t)
		{
			
			try
			{
				t.UserId = _userManager.GetUserId(User);
				t.Data = DateTime.Now;
				db.Tags.Add(t);
				db.SaveChanges();
				TempData["message"] = "Tagul a fost adaugata";
				return RedirectToAction("Index");
			}
			catch (Exception)
			{
				return View(t);
			}
		}

		[Authorize(Roles = "Admin")]
		public IActionResult Edit(int id)
		{
			Tag tag = db.Tags.Find(id);
			ViewBag.Tag = tag;
            return View(tag);

		}

		[Authorize(Roles = "Admin")]
		[HttpPost]
		public ActionResult Edit(int id, Tag requestTag)
		{
			Tag tag = db.Tags.Find(id);
            if(ModelState.IsValid)
			{
				tag.Denumire = requestTag.Denumire;
				db.SaveChanges();
				TempData["message"] = "Categoria a fost modificata!";
				return RedirectToAction("Index");
			}
			else
			{
				return View(requestTag);
			}
		}

		[Authorize(Roles = "Admin")]
		public ActionResult Delete(int id)
		{
			Tag tag = db.Tags.Find(id);
            if (!(tag.UserId == _userManager.GetUserId(User) || User.IsInRole("Admin")))
            {
                TempData["message"] = "Nu aveti dreptul sa faceti modificari asupra unui articol care nu va apartine";
                return RedirectToAction("Index");
            }
            db.Tags.Remove(tag);
			TempData["message"] = "Categoria a fost stearsa";
			 db.SaveChanges();
			return RedirectToAction("Index");
		}
	}
}

SocialMediaApp/Views/Shared/GroupInfo.cshtml
@model SocialMediaApp.Models.Group

<div class="card mx-auto mb-4" style="width: 100%;">
    <div class="card-header">
        <i class="bi bi-people-fill"></i> @Model.Nume
    </div>
    @if (@Model.Fotografie != null)
    {
        <div class="d-flex justify-content-center">
            <img src=@Model.Fotografie class="card-img-top post-image" alt="imagine atasata"/>
        </div>

    }
    <div class="card-body">
        @Model.Descriere
    </div>
</div>

SocialMediaApp/Views/Shared/PostInfo.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> signInManager
@inject RoleManager<IdentityRole> roleManager

<div class="mx-auto card w-auto h-auto">
    <div class="card-header button-container">
        <div class="fw-bold">
            <img src="@Model.User.Image" class="rounded-circle" style="width: 30px; height: 30px;" />
            @if (signInManager.IsSignedIn(User))
            {
                <a href="/Users/Details/@Model.User.Id" class="no-underline">
                    @Model.User.FirstName @Model.User.LastName
                </a>
            }

            else
            {
                <a href="/Home/Index" class="no-underline">
                    @Model.User.FirstName @Model.User.LastName
                </a>
            }
        </div>


        @if(@Model.TagId != null)
        {
            <a href="/Tags/Show/@Model.Tag.Id" class="bi bi-bookmark-fill no-underline"> @Model.Tag.Denumire</a>
        }
    </div>

    <div class="d-flex flex-row card-img-top justify-content-center">
        @if (@Model.Image != null)
        {
            <div>
                <img src=@Model.Image class="post-image" alt="imagine atasata">
            </div>

        }

        @* @if(@Model.Video != null) *@
        @* { *@
        @*     <div> *@
        @*         <iframe width="560" height="315" *@
        @*                 src="https://www.youtube.com/embed/@Model.Video" *@
        @*                 title="YouTube video player" frameborder="0" *@
        @*                 allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" *@
        @*                 allowfullscreen> *@
        @*         </iframe> *@

        @*     </div> *@
        @* } *@
    </div>

    <div class="card-body">
        <p class="card-text">
            @Html.Raw(Model.Continut)
        </p>
        <hr />

        @if (signInManager.IsSignedIn(User))
        {
            <div class="d-flex flex-row justify-content-lg-between">
                <form asp-controller="Posts" asp-action="Show" asp-route-id="@Model.Id" method="get">
                    <div>
                        <button class="btn btn-primary bi bi-chat-left-text fs-5" type="submit"> @Model.NrComments</button>

                    </div>
                </form>


                @if (User.IsInRole("Admin"))
                {
                    <form asp-controller="Likes" asp-action="ShowLikes" asp-route-id="@Model.Id" method="get">
                        <div>
                            <button class="btn btn-primary bi bi-heart fs-5" type="submit" id="@Model.Id"> @Model.NrLikes</button>
                        </div>
                    </form>
                }

                else 
                {
                    <form asp-controller="Likes" asp-action="Click" asp-route-id="@Model.Id" method="post">
                        <div>
                            <button class="btn btn-primary bi bi-heart fs-5 like" type="submit" id="@Model.Id"> @Model.NrLikes</button>
                            <input type="hidden" name="url" value="@($"{Context.Request.Path}{Context.Request.QueryString}")"/>

                        </div>
                    </form>

                }
            </div>
        
        }

        else 
        {
            <div class="d-flex flex-row justify-content-lg-between">
                <form asp-controller="Home" asp-action="Index" method="get">
                    <div>
                        <button class="btn btn-primary bi bi-chat-left-text fs-5" type="submit"> 
                            @Model.NrComments
                         </button>
                    </div>
                </form>



                <form asp-controller="Home" asp-action="Index" method="get">
                    <div>
                        <button class="btn btn-primary bi bi-heart fs-5" type="submit" id="@Model.Id"> @Model.NrLikes</button>
                    </div>
                </form>

            </div>
        
        }

       
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item"><i class="bi bi-calendar-check-fill"> @Model.Data.ToString("dd.MM.yyyy, HH:mm")</i></li>
        <li class="list-group-item"><i class="bi bi-geo-alt-fill"> @Model.Locatie</i></li>
    </ul>
</div>

SocialMediaApp/Views/Shared/TagInfo.cshtml
<div class="card-body">

    <h3 class="card-title alert-success py-3 px-3 rounded-2">
        @Model.Id
    </h3>

    <div class="card-text">@Model.Denumire</div>
    <div class="d-flex justify-content-between flex-row mt-5">
        <span class="alert-success">@Model.Data</span>
    </div>
</div>

SocialMediaApp/Views/Shared/_AccountLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SocialMediaApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/account.css" asp-append-version="true" />

    <!-- se include summernote css -->
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.9.0/dist/summernote-lite.min.css" rel="stylesheet">
</head>
<body>
    <div>
          @RenderBody()
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <!-- se include summernote js -->
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.9.0/dist/summernote-lite.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <!-- se include Summernote.js -->
    <script src="~/js/Summernote.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SocialMediaApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Kalopsia</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SocialMediaApp.styles.css" asp-append-version="true" />

    <!-- se include summernote css -->
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.9.0/dist/summernote-lite.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Posts" asp-action="Index">Kalopsia</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @if (SignInManager.IsSignedIn(User))
                    {

                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Posts" asp-action="Index">Postări</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Groups" asp-action="Index">Grupuri</a>
                            </li>

                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Tags" asp-action="Index">Etichete</a>
                                </li>
                            }

                        </ul>
                       
                    
                }
                    <partial name="_LoginPartialCustom" />
                </div>
               
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Kalopsia
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <!-- se include summernote js -->
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.9.0/dist/summernote-lite.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <!-- se include Summernote.js -->
    <script src="~/js/Summernote.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SocialMediaApp/Views/Shared/_LoginPartialCustom.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> signInManager
@inject UserManager<ApplicationUser> userManager

<ul class="navbar-nav ms-auto">

	@if(signInManager.IsSignedIn(User))
	{
		var userId = userManager.GetUserId(User);
		var user = await userManager.FindByIdAsync(userId);
		<li class="nav-item">
			<a class="nav-link text-dark bi bi-search" asp-area="" asp-controller="Users" asp-action="Search">
				Caută
			</a>
		</li>
		<li class="nav-item">
			<a class="nav-link text-dark bi bi-people-fill" asp-area="" asp-controller="Follows" asp-action="Index" asp-route-id="@userId">
				Prieteni
			</a>
		</li>
		<li class="nav-item">
			<a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Details" asp-route-id="@userId">
				<img src="@user.Image" class="rounded-circle" style="width: 30px; height: 30px;"/>
			</a>
		</li>
		<li class="nav-item">
			<a class="nav-link text-dark" asp-controller="Account" asp-action="Logout"><i class="bi bi-box-arrow-right"></i></a>
		</li>
	}

	else 
	{
		<li class="nav-item">
			<a class="nav-link text-dark" asp-controller="Account" asp-action="Login">Conectare</a>
		</li>

		<li class="nav-item">
			<a class="nav-link text-dark" asp-controller="Account" asp-action="Register">Înregistrare</a>
		</li>
	}


</ul>

SocialMediaApp/Views/Shared/_ShowUsers.cshtml
@if (ViewBag.Users == null || (ViewBag.UsersCt != null && ViewBag.UsersCt == 0))
{
	<div class="d-flex justify-content-center align-items-center vh-100">
		<div class="mb-3 fw-bold fs-1 bi bi-ban">
			Niciun utilizator găsit
		</div>
	</div>
}

else
{
		<div class="d-flex flex-column align-items-center" style="gap: 20px;">
		@foreach (var user in ViewBag.Users)
		{
			<div class="p-card card d-flex flex-row align-items-center w-75" style="padding: 10px; gap: 40px;" id="profileCard" data-user-id="@user.Id">
				<div>
					<img class="profile-image" src="@user.Image" />
				</div>
				<div>
					<div class="card-text fs-4">
						@user.FirstName @user.LastName
					</div>
				</div>
			</div>
		}
	</div>

}